spring:
  cloud:
    stream:
      function:
        bindings:
          recommendation-in-0: input
          recommendation-out-0: output
      bindings:
        input:
          destination: ${KAFKA_INPUT_TOPIC:user-info}
          group: group-1
          concurrency: 4
        output:
          destination: ${KAFKA_OUTPUT_TOPIC:recommendation-list}